/* Chat-Zeilen für die Stream-Konsole. Parodie, kein echter Chat. */
export const CHAT_LINES = [
  "kubabonuscom",
  "kubabonuscom code KUBA",
  "KUBABONUSCOM",
  "kubabonuscom lol",
  "kubabonuscom ez",
  "geh auf kubabonuscom",
  "kubabonuscom bruder",
  "kubabonuscom zurecht",
  "kubabonuscom HAHAHAHA",
  "kubabonuscom oder nix",
  "kubabonuscom spam",
  "kubabonuscom jetzt",
  "kubabonuscom go go go",
  "kubabonuscom ist der weg",
  "kubabonuscom xd",
  "kubabonuscom",
  "kubabonuscom code KUBA",
  "KUBABONUSCOM",
  "kubabonuscom lol",
  "kubabonuscom ez",
  "geh auf kubabonuscom",
  "kubabonuscom bruder",
  "kubabonuscom zurecht",
  "kubabonuscom HAHAHAHA",
  "kubabonuscom oder nix",
  "kubabonuscom spam",
  "kubabonuscom jetzt",
  "kubabonuscom go go go",
  "kubabonuscom ist der weg",
  "kubabonuscom xd",
  "kubabonuscom",
  "kubabonuscom code KUBA",
  "KUBABONUSCOM",
  "kubabonuscom lol",
  "kubabonuscom ez",
  "geh auf kubabonuscom",
  "kubabonuscom bruder",
  "kubabonuscom zurecht",
  "kubabonuscom HAHAHAHA",
  "kubabonuscom oder nix",
  "kuba war mal radiant und jetzt sitzt er hier",
  "von valo zu slots, was für ein arc",
  "der hat iso gemained. zurecht",
  "immortal 3 hardstuck, das sagt alles",
  "sein aim war damals schon ass",
  "kuba hat valo verlassen weil valo ihn verlassen hat",
  "er hat den rank verloren, jetzt verliert er geld",
  "damals ace, heute keine 5 gleichen",
  "kuba erklärt uns gleich wieder crosshair placement",
  "der mann hat 4000 stunden valo und trifft trotzdem nix",
  "ex valo pro btw",
  "er sagt pro, er meint premier bronze",
  "valo aufgehört weil zu viele cheater. klar kuba",
  "kuba hat seinen sheriff verkauft für den bonus buy",
  "reyna one trick energie",
  "der spielt slots wie er valo gespielt hat. lose lose",
  "kuba peekt den spin wie ne ecke auf ascent",
  "er hat nie gespiket, nur gespinnt",
  "ex-valo spieler die slots spielen sind ein eigener menschenschlag",
  "damals 0/12 heute 0/12 spins",
  "kuba mit dem klassischen whiff",
  "er zieht wie er damals gezogen hat: daneben",
  "valo rank gone, bankroll gone, hair next",
  "er hat gesagt er kommt zurück wenn er radiant ist. lol",
  "kuba war der einzige der in silber geraget hat",
  "sein team hat ihn gereportet, zurecht",
  "spike planted, konto exploded",
  "clutch or kick. heute kick",
  "er hat mehr zeit im slot als in der range verbracht",
  "valo deinstalliert, würde nicht ändern",
  "kuba ist der grund warum es einen surrender button gibt",
  "operator gekauft, ecke geheld, nix getroffen. wie hier",
  "ex immortal, current broke",
  "er hat damals den crosshair code verkauft für 5 euro",
  "kuba hat ein ganzes team zum aufhören gebracht",
  "zurecht",
  "zurecht bruder",
  "völlig zurecht",
  "zurecht und nicht anders",
  "das ist zurecht so",
  "zurecht verloren",
  "verdient",
  "hart verdient",
  "selbst schuld",
  "das ist so peinlich",
  "peinlich aber lustig",
  "niemand ist überrascht",
  "HAHAHAHA",
  "HAHAHAHAHA",
  "HAHAHAHAHAHA",
  "hahaha nein",
  "HAHA er weint gleich",
  "HAHAHA das board ist tot",
  "ich lach mich weg",
  "bro das war schmerzhaft",
  "aua",
  "schmerz",
  "das tat weh beim zuschauen",
  "ich schau weg",
  "das ist kein spiel mehr das ist therapie",
  "er redet sich das schön",
  "copium level 9000",
  "kuba erklärt uns warum das eigentlich gut war",
  "lüg dich nicht an",
  "du bist nicht unlucky du bist schlecht",
  "skill issue",
  "hardstuck in jedem spiel",
  "sag nochmal du hast das im griff",
  "niemand zwingt dich",
  "du hast es doch selber gewollt",
  "und wieder nix",
  "das war absehbar",
  "hab ich gesagt",
  "hab ichs nicht gesagt",
  "hab ich literally gesagt",
  "ich hab im chat gewarnt",
  "screenshot ist gemacht",
  "clip läuft",
  "das kommt ins highlight",
  "das kommt in den jahresrückblick",
  "cluster wo",
  "5 gleiche wären mal was",
  "tumble bitte",
  "tumble tumble tumble",
  "der tumble kommt nicht",
  "das board ist tot",
  "totes board",
  "board sieht ok aus",
  "board sieht krank aus",
  "ein cluster mehr und es geht ab",
  "multi wo",
  "kein einziger multi",
  "x2 danke auch",
  "x2 ist ne beleidigung",
  "der x2 troll",
  "ich will 500x sehen",
  "x500 einmal bitte",
  "multi über 100 wäre nice",
  "der multi ist auf nem toten board gelandet klar",
  "multi ohne cluster ist das neue tilt",
  "scatter",
  "SCATTER",
  "zwei scatter reicht nicht",
  "drei scatter und dann nix. jedes mal",
  "4 scatter oder ich geh",
  "bonus buy jetzt",
  "kauf endlich",
  "kauf den super buy du feigling",
  "500x buy oder nichts",
  "er traut sich nicht",
  "ante 2 an du hast nix zu verlieren",
  "ante bringts eh nicht",
  "ante 1 ist copium",
  "super spin 2 mal probieren",
  "die freispiele sind ne falle",
  "freispiele mit x1 global. peak",
  "global multi bei 3 nach 10 spins ist crazy work",
  "tanga cluster wäre lore accurate",
  "testo cluster wo",
  "peptides sind das neue gold",
  "whey zahlt nicht mal die miete",
  "die karten symbole zahlen nix",
  "nur k und q das ganze spiel",
  "ass symbol spam",
  "warum kommt nur j",
  "max win ist 10000x nur damit du weißt was du nie siehst",
  "hit rate 22 prozent spürt man",
  "der rtp ist 96 aber nicht für dich",
  "LOS KUBA",
  "LOS LOS LOS",
  "GEHT",
  "GEHT AB",
  "JAAAA",
  "OMG",
  "OMFG",
  "BRUDER",
  "BRUDERRR",
  "WAS",
  "WAS IST DAS",
  "ich zitter",
  "meine hände zittern",
  "hände weg von der maus",
  "nicht atmen",
  "keiner atmet",
  "das ist es",
  "das war es",
  "ES GEHT LOS",
  "letzter spin schwöre",
  "der letzte spin ist nie der letzte",
  "kuba ruhig bleiben",
  "atme",
  "er atmet nicht mehr",
  "er ist blass geworden",
  "wer schaut noch",
  "2000 leute schauen ihm beim verlieren zu",
  "beste unterhaltung",
  "kostenloser content",
  "ich sollte lernen",
  "ich hab morgen prüfung",
  "ich hab morgen früh schicht",
  "es ist 4 uhr",
  "mein akku ist bei 3 prozent aber ich bleib",
  "erstmal einen shaker",
  "shaker ist leer",
  "noch ein scoop dann läufts",
  "kuba trink wasser",
  "er hat seit 6 stunden nicht getrunken",
  "kuba iss was",
  "kuba schlaf",
  "mods bannt mich",
  "ich bin schon wieder timeout",
  "warum bin ich noch hier",
  "ich hab mich selbst enttäuscht",
  "first",
  "zu spät",
  "habt ihr das gesehen",
  "hab ich gerade nicht geblinzelt",
  "der chat ist schneller als seine reaktion",
  "chat carry",
  "chat hatte recht",
  "chat hat immer recht",
  "neuer clip",
  "clip it",
  "CLIP IT",
  "das muss auf tiktok",
  "das geht viral",
  "HAHAHA das board ist tot lol",
  "kuba trink wasser ???",
  "digga tanga cluster wäre lore accurate ez",
  "alter LOS KUBA lmao",
  "ok aber das muss auf tiktok",
  "kubaaa mit dem klassischen whiff lol",
  "wallah peptides sind das neue gold",
  "DAS BOARD IST TOT",
  "wallah shmerz",
  "alter kuba erklärt uns gliech wieder crosshair placement",
  "er hat damals den crosshair code verkauft für 5 euro ez",
  "wallah ich hab morgen früh schicht ez!!",
  "ok aber anteee 1 ist copium lol",
  "digga clutch or kick. heute kick 💀 zurecht",
  "FREISPIELE MIT X1 GLOBAL. PEAK ez",
  "tumble tumble tumble zurecht",
  "kubaaa schlaf lol",
  "500X BUY ODER NICHTS zurecht",
  "alter kubaaa war der einzige der in silber geraget hat 💀",
  "ok aber neuer clip",
  "das ist so peinlich zurecht",
  "alter first lol",
  "wallah sein team hat ihn gereportet, zurecht",
  "multi wo ez",
  "wallah hab ichs nicht gesagt lmao",
  "alter chat hatte recht",
  "alter kauf den super buy du fiegling??",
  "DAMALS 0/12 HEUTE 0/12 SPINS xd",
  "bro JAAAAAA lol",
  "du bist nicht unlucky du bist schlecht 💀",
  "ass symbol spam lol hart",
  "HAHA er weint gleich zurecht",
  "bro zurecht lmao",
  "SEIN AIM WAR DAMALS SCHON ASS",
  "ok aber testo cluster wo zurecht",
  "wallah ich sollteee lernen",
  "HAHA er weint gleich 💀 hab",
  "tumbleee tumble tumble chat",
  "niemand zwingt dich ez",
  "digga ante 2 an du hast nix zu verlieren lmao",
  "digga SHAKER IST LEER",
  "WARUM BIN ICH NOCH HIER xd",
  "digga der tumbleee kommt nicht 💀",
  "wer schaut noch 💀",
  "digga chat hatte recht lmao",
  "ok aber valo rank gone, bankroll gone, hair next",
  "bro kuba schlaf",
  "das geht viral lmao",
  "digga tumble bitte lmao",
  "CLIP IT 💀",
  "alter ER ZIEHT WIE ER DAMALS GEZOGEN HAT: DANEBEN",
  "5 glieche wären mal was lol",
  "wallah zurecht",
  "ok aber hab ich gerade nicht geblinzelt",
  "bro clutch or kick. heute kick ez",
  "digga testo cluster wo",
  "x500 einmal bitte 💀",
  "DER RTP IST 96 ABER NICHT FÜR DICH",
  "bro er zieht wieee er damals gezogen hat: daneben lol",
  "noch ein scoop dann läufts lmao …",
  "tumble tumble tumble lmao",
  "ok aber VALO RANK GONE, BANKROLL GONE, HAIR NEXT lol",
  "alter ich hab morgen früh shicht zurecht",
  "wallah valo rank gone, bankroll gone, hair next",
  "clutch or kick. heute kick ???",
  "ich hab morgen prüfung zurecht",
  "ok aber warum kommt nur j",
  "bro CLIP IT",
  "multiii wo",
  "ante bringts eh nicht 💀",
  "ok aber KUBA SCHLAF 💀",
  "EIN CLUSTER MEHR UND ES GEHT AB …",
  "ok aber bonus buy jetzt lol",
  "wallah ich bin schon wieder timeout xd",
  "wallah das war es zurecht peptides",
  "es ist 4 uhr xd HAHAHA",
  "ok aber clutch or kick. heute kick 💀",
  "wallah ex immortal, current broke 💀",
  "alter reyna one trick energie",
  "digga ER ZIEHT WIE ER DAMALS GEZOGEN HAT: DANEBEN lol",
  "ich hab mich selbst enttäuscht lol",
  "ICH HAB MICH SELBST ENTTÄUSCHT xd",
  "alter sein team hat ihn gereportet, zurecht zurecht !!!",
  "das war absehbar ez",
  "immortal 3 hardstuck, das sagt alles lmao",
  "bro HAHAHAHAHA zurecht",
  "zu spät zurecht",
  "alter ante 2 an du hast nix zu verlieren lmao",
  "zwei scatter reicht nicht zurecht",
  "bro das ist so peinlich",
  "wallah chat carry lol",
  "digga von valo zu slots, was für ien arc xd",
  "digga kubaaa hat ein ganzes team zum aufhören gebracht",
  "ok aber ES IST 4 UHR",
  "ok aber meine hände zittern zurecht",
  "bro shaker ist leer",
  "X2 DANKE AUCH ez",
  "er redet sich das schön zurecht hart",
  "ok aber atme ez",
  "er hat gesagt er kommt zurück wenn er radiant ist. lol lol",
  "HAHA ER WEINT GLEICH zurecht",
  "5 gleiche wären mal was lmao",
  "bro der rtp ist 96 aber nicht für dich 💀",
  "alter und wieder nix",
  "wallah cluster wo ez",
  "valooo deinstalliert, würde nicht ändern",
  "bro der x2 troll lmao",
  "bro das war schmerzhaft lol",
  "wallah händeee weg von der maus",
  "kein einziger multi zurecht",
  "digga DAS WAR ABSEHBAR 💀",
  "digga das kommt ins highlight 💀",
  "ich bin schon wieder timeout ez",
  "valo aufgehört weil zu viele cheater. klar kuba zurecht",
  "digga x2 ist neee beleidigung ez",
  "ok aber KUBA WAR DER EINZIGE DER IN SILBER GERAGET HAT",
  "digga x2 ist ne beleidigung",
  "alter ante 1 ist copium 💀",
  "digga wer schaut noch",
  "ok aber er hat seit 6 stunden nicht getrunken",
  "spike planted, konto exploded zurecht",
  "digga NIEMAND ZWINGT DICH zurecht",
  "alter das war es ez",
  "alter operator gekauft, ecke geheld, nix getroffen. wie hier",
  "HABT IHR DAS GESEHEN",
  "warum kommt nur j ez",
  "alter kuba schlaf lmao er",
  "damals ace, heute keine 5 gleichen xd",
  "digga der chat ist schneller als seine reaktion lmao",
  "TESTO CLUSTER WO lmao",
  "alter sag nochmal du hast das im griff",
  "er hat mehr zeit im slot als in der range verbracht zurecht",
  "alter damals ace, heute keine 5 gleichen",
  "bro kostenloser content xd es",
  "MEINE HÄNDE ZITTERN xd",
  "bro ich schau weg",
  "kubaaa war der einzige der in silber geraget hat xd",
  "bro zu spät zurecht",
  "das tat weh beim zuschauen lmao",
  "sein team hat ihn gereportet, zurecht ez",
  "ok aber chat carry zurecht",
  "clip it lmao",
  "wallah er ist blass geworden ez",
  "er hat damals den crosshair codeee verkauft für 5 euro lol ich",
  "kuba hat seinen sheriff verkauft für den bonus buy lol",
  "ok aber kuba schlaf",
  "clutch or kick. heute kick ez",
  "bro selbst schuld",
  "alter zurecht und nicht anders 💀 ???",
  "der spielt slots wie er valo gespielt hat. lose lose lmao",
  "beste unterhaltung 💀",
  "ok aber DAS KOMMT IN DEN JAHRESRÜCKBLICK",
  "bro ex valo pro btw",
  "ok aber nur k und q das ganze spiel",
  "UND WIEDER NIX 💀",
  "bro niemand ist überrascht zurecht",
  "alter HARDSTUCK IN JEDEM SPIEL",
  "ok aber das kommt ins highlight",
  "DAS IST SO PEINLICH",
  "zurecht und nicht anders lol",
  "bro ich bin schon wieder timeout",
  "bro der chat ist schneller als seine reaktion",
  "kuba ist der grund warum es einen surrender button gibt zurecht",
  "clip läuft ez!! noch",
  "ok aber kuba war der einzige der in silber geraget hat ich",
  "wallah tumble bitte",
  "TUMBLE TUMBLE TUMBLE",
  "bro ich sollte lernen",
  "whey zahlt nicht mal die miete ez",
  "digga das ist so peinlich 💀",
  "digga hab ich gerade nicht geblinzelt ez",
  "kuba ruhig bleiben 💀",
  "bro reyna one trick energie",
  "kuba hat ien ganzes team zum aufhören gebracht zurecht !!!",
  "der multi ist auf nem toten board gelandet klar zurecht",
  "alter das kommt in den jahresrückblick zurecht",
  "alter skill issue??",
  "ok aber HAB ICH GESAGT xd er",
  "wallah x2 ist ne beleidigung",
  "wallah x2 danke auch",
  "alter kuba trink wasser 💀",
  "wallah WAS IST DAS lmao",
  "der mann hat 4000 stunden valo und trifft trotzdem nix lmao",
  "alter clutch or kick. heute kick lol",
  "bro cluster wo xd",
  "tumble bitte zurecht",
  "cluster wooo lmao …",
  "bro hahaha nein",
  "alter multi ohne cluster ist das neue tilt",
  "dreiii scatter und dann nix. jedes mal lol … BRUDERRR",
  "ok aber valo aufgehört weil zu viele cheater. klar kuba",
  "wallah ICH WILL 500X SEHEN lmao",
  "wallah reyna one trick energie ???",
  "ER HAT MEHR ZEIT IM SLOT ALS IN DER RANGE VERBRACHT",
  "von valo zu slots, was für ein arc lmao",
  "ex immortal, current broke lol",
  "HAHA er weint gleich??",
  "neuer clip ez",
  "ok aber mods bannt mich lmao",
  "wallah er hat damals den crosshair codeee verkauft für 5 euro ez!!",
  "ok aber hardstuck in jedem spiel",
  "kuba iss was 💀",
  "wallah multi über 100 wäre nice ez",
  "kubaaa mit dem klassischen whiff",
  "digga kauf den super buy du feigling lol",
  "alter multi ohne cluster ist das neue tilt lmao",
  "ok aber chat hat immer recht",
  "operator gekauft, ecke geheld, nix getroffen. wie hier lol",
  "alter reyna one trick energie zurecht",
  "HAHAHAHAHA lmao scatter",
  "digga hab ich gesagt",
  "ok aber das ist es zurecht",
  "hit rateee 22 prozent spürt man xd",
  "ok aber kien einziger multi zurecht",
  "ok aber er traut sich nicht zurecht",
  "digga die freispiele sind ne falle lol",
  "bro DAS WAR ABSEHBAR",
  "OMFG 💀",
  "hahaha nein 💀",
  "besteee unterhaltung 💀",
  "bro skill issue xd",
  "screenshot ist gemacht zurecht",
  "hab ich literally gesagt ez",
  "wallah der letzte spin ist nie der letzte ez",
  "bro spike planted, konto exploded",
  "ich sollteee lernen xd",
  "alter bonus buy jetzt zurecht",
  "CLIP LÄUFT",
  "wallah ich zitter",
  "ER HAT NIE GESPIKET, NUR GESPINNT",
  "bro wer schaut noch",
  "bro VÖLLIG ZURECHT",
  "bro der tumble kommt nicht lmao",
  "ok aber ER HAT DAMALS DEN CROSSHAIR CODE VERKAUFT FÜR 5 EURO lmao",
  "digga ich hab morgen prüfung ez",
  "ok aber KEINER ATMET lmao",
  "max win ist 10000x nur damit du weißt was du nie siehst zurecht",
  "ZURECHT UND NICHT ANDERS lol",
  "wallah x500 einmal bitte 💀",
  "ok aber ICH HAB MICH SELBST ENTTÄUSCHT",
  "digga kostenloser content ez",
  "ok aber tangaaa cluster wäre lore accurate xd",
  "spike planted, konto exploded lmao",
  "bro kuba war der einzige der in silber geraget hat ez",
  "wallah der hat iso gemained. zurecht lol",
  "wallah warum bin ich noch hier",
  "digga max win ist 10000x nur damit du weißt was du nie siehst ez",
  "bro kuba war mal radiant und jetzt sitzt er hier",
  "shaker ist leer xd",
  "neuer clip lol",
  "völlig zurecht ez",
  "GEHT zurecht",
  "ein cluster mehr und es geht ab ez",
  "digga die freispiele sind ne falle xd",
  "DER X2 TROLL",
  "HAHAHA das board ist tot ez",
  "zu spät ez",
  "JAAAA xd",
  "digga ante 2 an du hast nix zu verlieren",
  "bro er sagt pro, er meint premier bronze lmao",
  "ZWEI SCATTER REICHT NICHT ez",
  "alter CLIP LÄUFT ez",
  "global multi bei 3 nach 10 spins ist crazy work lmao",
  "schmerz lmao",
  "digga bro das war shmerzhaft",
  "CLUSTER WO lol",
  "valo deinstalliert, würde nicht ändern xd",
  "alter der mann hat 4000 stunden valo und trifft trotzdem nix",
  "digga 2000 LEUTE SCHAUEN IHM BEIM VERLIEREN ZU zurecht",
  "500X BUY ODER NICHTS",
  "bro bonus buy jetzt lol …",
  "bro das war schmerzhaft zurecht",
  "das kommt in den jahresrückblick zurecht",
  "digga immortal 3 hardstuck, das sagt alles",
  "bro keiner atmet",
  "ok aber spike planted, konto exploded 💀",
  "digga zweiii scatter reicht nicht ez",
  "HAHAHA das board ist tot 💀",
  "digga drei scatter und dann nix. jedes mal",
  "kuba hat seinen sheriff verkauft für den bonus buy 💀",
  "4 scatter oder ich geh 💀",
  "alter kubaaa hat valo verlassen weil valo ihn verlassen hat",
  "testo cluster wo 💀",
  "multi ohne cluster ist das neue tilt xd",
  "digga KEINER ATMET xd",
  "kauf den super buy du feigling 💀",
  "er sagt pro, er meint premier bronze lmao",
  "GEHT AB lmao",
  "ex-valo spieler die slots spielen sind ein eigener menschenschlag ez",
  "HAHA er weint gleich lmao!!",
  "kuba ist der grund warum es einen surrender button gibt 💀",
  "alter KOSTENLOSER CONTENT lol",
  "alter er hat seit 6 stunden nicht getrunken zurecht",
  "alter peinlich aber lustig zurecht !!!",
  "shaker ist leer lmao",
  "kuba hat ein ganzes team zum aufhören gebracht ez",
  "bro CHAT CARRY",
  "alter der chat ist schneller als seine reaktion lol",
  "wallah kuba ruhig bleiben xd",
  "zurecht bruder 💀",
  "wallah das ist kein spiel mehr das ist therapieee zurecht",
  "bro er hat gesagt er kommt zurück wenn er radiant ist. lol xd",
  "digga valo deinstalliert, würde nicht ändern ez",
  "KEINER ATMET",
  "bro der tumble kommt nicht zurecht",
  "digga ZWEI SCATTER REICHT NICHT",
  "warum kommt nur j zurecht",
  "bro KUBA PEEKT DEN SPIN WIE NE ECKE AUF ASCENT ???",
  "hab ichs nicht gesagt zurecht",
  "alter selbst schuld lmao",
  "wallah VALO AUFGEHÖRT WEIL ZU VIELE CHEATER. KLAR KUBA lmao",
  "max win ist 10000x nur damit du wießt was du nie siehst",
  "testo cluster wo xd",
  "digga KUBA HAT SEINEN SHERIFF VERKAUFT FÜR DEN BONUS BUY",
  "digga und wieder nix lol",
  "zurecht lol",
  "bro testo cluster wo xd der",
  "cluster wooo",
  "mein akkuuu ist bei 3 prozent aber ich bleib",
  "SCATTER 💀",
  "auaaa ez",
  "digga VALO RANK GONE, BANKROLL GONE, HAIR NEXT",
  "bro NEUER CLIP lmao",
  "wallah das muss auf tiktok xd",
  "kubaaa erklärt uns warum das eigentlich gut war lmao",
  "bro DER LETZTE SPIN IST NIE DER LETZTE",
  "digga cluster wo",
  "ok aber er traut sich nicht ez",
  "alter aua lmao?? ich",
  "wallah BOARD SIEHT OK AUS",
  "digga der spielt slots wie er valo gespielt hat. lose lose",
  "wallah ich sollte lernen",
  "digga kauf den super buy du feigling",
  "ok aber kuba hat valo verlassen weil valo ihn verlassen hat xd",
  "das tat weh beim zuschauen zurecht!!",
  "bro nur k und q das ganze spiel",
  "alter tanga cluster wäre lore accurate 💀",
  "bro 4 scatter oder ich geh ez",
  "er hat gesagt er kommt zurück wenn er radiant ist. lol lmao",
  "wallah copium level 9000 ez",
  "alter hab ichs nicht gesagt",
  "max win ist 10000x nur damit du weißt was du nie siehst ez",
  "kubaaa trink wasser lmao",
  "HAB ICH GESAGT",
  "alter das ist kein spiel mehr das ist therapie",
  "ok aber ich sollte lernen lol",
  "ich will 500x sehen …",
  "first lmao der",
  "ok aber er hat nie gespiket, nur gespinnt",
  "SCATTER ez",
  "ein cluster mehr und es geht ab 💀",
  "bonus buy jetzt lmao",
  "bro kein einziger multi lol",
  "ok aber LOS KUBA",
  "digga ES GEHT LOS lol",
  "ok aber KUBA WAR MAL RADIANT UND JETZT SITZT ER HIER xd",
  "ok aber bro das war schmerzhaft xd",
  "wallah habt ihr das gesehen",
  "wallah ICH HAB MORGEN PRÜFUNG",
  "er hat gesagt er kommt zurück wenn er radiant ist. lol zurecht",
  "ok aber tumble bitte 💀",
  "wallah das tat weh beim zuschauen",
  "GEHT lol",
  "bro WAS ez",
  "mods bannt mich 💀",
  "digga x500 einmal bitte 💀 völlig",
  "wallah schmerz ez",
  "bro MEIN AKKU IST BEI 3 PROZENT ABER ICH BLEIB 💀",
  "wallah warum bin ich noch hier lmao",
  "global multi bei 3 nach 10 spins ist crazy work lol",
  "wallah zurecht bruder lol",
  "bro immortal 3 hardstuck, das sagt alles lol",
  "digga SAG NOCHMAL DU HAST DAS IM GRIFF lmao",
  "das ist es ez",
  "das war es ez",
  "KUBA WAR MAL RADIANT UND JETZT SITZT ER HIER zurecht",
  "wallah das ist es",
  "digga DAS KOMMT IN DEN JAHRESRÜCKBLICK",
  "wallah ER SAGT PRO, ER MEINT PREMIER BRONZE ez",
  "board sieht ok aus xd",
  "digga das ist es lol",
  "wallah valooo deinstalliert, würde nicht ändern lmao",
  "wallah OMFG",
  "bro hab ich gesagt ez",
  "ok aber er hat den rank verloren, jetzt verliert er geld lmao",
  "kuba shlaf lol??",
  "ex-valo spieler die slots spielen sind ein eigener menschenschlag lmao",
  "ok aber operator gekauft, ecke geheld, nix getroffen. wie hier",
  "wallah niemand ist überrascht xd",
  "alter JAAAA",
  "global multi bei 3 nach 10 spins ist crazy work hände",
  "kuba iss was zurecht",
  "wallah HAHA er weint gleich lmao",
  "tanga cluster wäre lore accurate zurecht",
  "ok aber kuba peekt den spin wie ne ecke auf ascent lol",
  "bro ante bringts eh nicht",
  "bro 2000 leute schauen ihm beim verlieren zu 💀",
  "alter ich hab morgen früh schicht xd",
  "bro hab ich gerade nicht geblinzelt lol",
  "alter kuba hat seinen sheriff verkauft für den bonus buy lmao",
  "lüg dich nicht an 💀",
  "ok aber er hat mehr zeit im slot als in der rangeee verbracht",
  "ok aber er hat mehr zeit im slot als in der range verbracht lol",
  "ich schauuu weg ez",
  "das geht viral zurecht",
  "bro es ist 4 uhr",
  "ok aber 4 scatter oder ich geh !!!",
  "ok aber kubaaa hat ein ganzes team zum aufhören gebracht xd",
  "chat carry 💀",
  "kubaaa ruhig bleiben",
  "alter ich lach mich weg zurecht",
  "bro das geht viral lmao",
  "neuer clip 💀",
  "atme lmao …",
  "digga DER MANN HAT 4000 STUNDEN VALO UND TRIFFT TROTZDEM NIX lmao",
  "damals aceee, heute keine 5 gleichen",
  "bro board sieht ok aus xd",
  "ER ZIEHT WIE ER DAMALS GEZOGEN HAT: DANEBEN lol kuba",
  "valo rank gone, bankroll gone, hair next lmao",
  "bro er hat seit 6 stunden nicht getrunken 💀",
  "kubaaa hat ein ganzes team zum aufhören gebracht xd",
  "drei scatter und dann nix. jedes mal lmao",
  "tumbleee bitte",
  "alter kuba war der einzige der in silber geraget hat 💀",
  "chat hat immer recht lol",
  "wallah nur k und q das ganze spiel zurecht",
  "digga ich sollte lernen zurecht",
  "wallah keiner atmet",
  "alter DAS KOMMT IN DEN JAHRESRÜCKBLICK",
  "bro ich hab im chat gewarnt lmao",
  "digga freispiele mit x1 global. peak",
  "kauf den super buy du feigling xd",
  "bro first",
  "HAB ICH LITERALLY GESAGT ez",
  "wallah SCATTER??",
  "NOCH EIN SCOOP DANN LÄUFTS",
  "wer schaut noch !!!",
  "alter ZWEI SCATTER REICHT NICHT 💀",
  "digga NUR K UND Q DAS GANZE SPIEL zurecht??",
  "ok aber HAHAHA NEIN",
  "kauf den super buy du feigling lmao",
  "bro board sieht ok aus zurecht!!",
  "bro mein akku ist bei 3 prozent aber ich bleib",
  "wer schaut noch xd",
  "digga hab ich gesagt ez",
  "ok aber cluster wo",
  "alter niemand ist überrascht lmao",
  "ok aber KUBA IST DER GRUND WARUM ES EINEN SURRENDER BUTTON GIBT?? bro",
  "dreiii scatter und dann nix. jedes mal",
  "digga verdient zurecht",
  "wallah das war es",
  "ok aber habt ihr das gesehen",
  "BRUDERRR ez",
  "digga bonus buy jetzt",
  "reyna one trick energie 💀",
  "digga multi ohne cluster ist das neue tilt zurecht",
  "wallah screenshot ist gemacht",
  "hart verdient lol",
  "ok aber hahaha nein",
  "digga kuba hat seinen sheriff verkauft für den bonus buy!!",
  "alter händeee weg von der maus xd",
  "alter GEHT",
  "ok aber hab ich gerade nicht geblinzelt 💀",
  "operator gekauft, ecke geheld, nix getroffen. wie hier lmao",
  "digga und wieder nix zurecht",
  "ok aber x500 einmal bitte lmao",
  "alter duuu hast es doch selber gewollt xd",
  "ok aber HARDSTUCK IN JEDEM SPIEL xd",
  "digga der mann hat 4000 stunden valo und trifft trotzdem nix ez",
  "ok aber er atmet nicht mehr",
  "ok aber er hat den rank verloren, jetzt verliert er geld 💀",
  "HAHAHA das board ist tot xd",
  "digga spike planted, konto exploded lol",
  "bro der mann hat 4000 stunden valo und trifft trotzdem nix ???",
  "SUPER SPIN 2 MAL PROBIEREN lol",
  "digga hardstuck in jedem spiel 💀",
  "alter DAS WAR ABSEHBAR 💀 ???",
  "VALO RANK GONE, BANKROLL GONE, HAIR NEXT",
  "alter sag nochmal du hast das im griff lmao",
  "bro ER SAGT PRO, ER MEINT PREMIER BRONZE zurecht",
  "pienlich aber lustig ez",
  "alter beste unterhaltung",
  "der letzte spin ist nie der letzte zurecht",
  "bro damals 0/12 heute 0/12 spins",
  "x500 ienmal bitte zurecht",
  "von valo zu slots, was für ein arc xd",
  "ante bringts eh nicht!!",
  "500x buy oder nichts zurecht",
  "multi wo ez der",
  "meine hände zittern ez",
  "bro SELBST SCHULD zurecht",
  "bro hab ichs nicht gesagt ez",
  "alter du bist nicht unlucky du bist schlecht lol",
  "digga GEHT 💀",
  "bro nur k und q das ganze spiel xd",
  "ok aber HAHAHAHAHA 💀",
  "SHAKER IST LEER 💀",
  "zurecht bruder xd",
  "alter tangaaa cluster wäre lore accurate xd",
  "bro super spin 2 mal probieren ez",
  "bro whey zahlt nicht mal die miete??",
  "X2 IST NE BELEIDIGUNG",
  "copium level 9000 lmao",
  "alter ich will 500x sehen",
  "digga kuba hat valo verlassen weil valo ihn verlassen hat zurecht??",
  "digga das war absehbar lmao",
  "ok aber kuba ist der grund warum es einen surrender button gibt",
  "sein aim war damals schon ass lmao",
  "wallah CHAT HATTE RECHT",
  "ex immortal, current brokeee lol",
  "ok aber ich zitter kuba",
  "kuba war der einzige der in silber geraget hat lol",
  "totes board lmao",
  "ex immortal, current broke lmao",
  "alter spike planted, konto exploded",
  "ANTE 1 IST COPIUM zurecht",
  "ok aber clip läuft lmao",
  "bro ich will 500x sehen",
  "bro nur k und q das ganze spiel lmao",
  "DAS WAR ABSEHBAR 💀",
  "wallah BRUDERRR xd …",
  "peptides sind das neue gold lol",
  "alter ich sollte lernen",
  "digga damals ace, heute kiene 5 gleichen zurecht",
  "ok aber first 💀",
  "UND WIEDER NIX ez",
  "ER HAT NIE GESPIKET, NUR GESPINNT ez",
  "alter VERDIENT",
  "reyna one trick energie lol",
  "bro DAS KOMMT INS HIGHLIGHT lol",
  "zurecht verloren lol",
  "hit rateee 22 prozent spürt man zurecht",
  "alter board sieht ok aus lol",
  "wallah hab ich literally gesagt",
  "digga zurecht bruder",
  "alter screenshot ist gemacht ez",
  "sag nochmal du hast das im griff lol ???",
  "BRUDERRR lol",
  "alter er zieht wie er damals gezogen hat: daneben 💀",
  "alter und wieder nix ez",
  "alter niemand ist überrascht",
  "alter clip läuft … selbst",
  "digga LOS LOS LOS lol",
  "kostenloser content 💀",
  "wallah ich will 500x sehen",
  "bro er redet sich das schön",
  "der letzte spin ist nie der letzte ez",
  "digga KUBA ISS WAS xd",
  "X500 EINMAL BITTE lol",
  "alter copium level 9000",
  "wallah CLIP IT xd",
  "sag nochmal duuu hast das im griff",
  "wallah CHAT HAT IMMER RECHT lmao BRUDER",
  "digga BRUDER xd",
  "wallah MULTI WO lmao",
  "MULTI WO",
  "wallah multi ohne cluster ist das neue tilt xd",
  "LOS KUBA ez",
  "selbst schuld 💀",
  "erstmal ienen shaker lol",
  "alter verdient ich",
  "kuba trink wasser zurecht",
  "digga peptides sind das neue gold",
  "wallah board sieht ok aus",
  "der hat iso gemained. zurecht zurecht …",
  "shaker ist leer 💀",
  "ER REDET SICH DAS SCHÖN zurecht ???",
  "niemand zwingt dich 💀",
  "alter kostenloser content zurecht",
  "DREI SCATTER UND DANN NIX. JEDES MAL",
  "valooo rank gone, bankroll gone, hair next",
  "ok aber kostenloser content ez",
  "wallah clip it",
  "ok aber du hast es doch selber gewollt",
  "valo aufgehört weil zu viele cheater. klar kuba 💀",
  "ex-valo spieler die slots spielen sind ein eigener menschenschlag zurecht",
  "ich sollte lernen 💀",
  "alter duuu hast es doch selber gewollt ez",
  "niemand zwingt dich xd",
  "wallah er sagt pro, er meint premier bronze",
  "KUBA HAT SEINEN SHERIFF VERKAUFT FÜR DEN BONUS BUY ez",
  "digga kubaaa iss was lol",
  "der rtp ist 96 aber nicht für dich lmao",
  "alter operator gekauft, ecke geheld, nix getroffen. wie hier zurecht",
  "digga kuba ruhig bleiben",
  "ok aber HAB ICHS NICHT GESAGT",
  "wallah er hat mehr zeit im slot als in der range verbracht lmao",
  "atmeee lol",
  "ok aber hände weg von der maus",
  "DER MULTI IST AUF NEM TOTEN BOARD GELANDET KLAR",
  "alter JAAAA ez",
  "wallah duuu bist nicht unlucky du bist schlecht",
  "wallah ex valo pro btw ez",
  "er sagt pro, er meint premier bronze xd",
  "bro chat hatte recht",
  "digga der hat iso gemained. zurecht ez",
  "die friespiele sind ne falle xd",
  "ok aber ich sollte lernen xd",
  "digga der tumble kommt nicht lol",
  "BRUDER 💀",
  "ok aber zurecht bruder zurecht",
  "ok aber board sieht krank aus zurecht",
  "das board ist tot ez",
  "alter KUBA ERKLÄRT UNS GLEICH WIEDER CROSSHAIR PLACEMENT",
  "IMMORTAL 3 HARDSTUCK, DAS SAGT ALLES …",
  "kuba schlaf ez HAHAHAHAHA",
  "ok aber das kommt in den jahresrückblick",
  "wallah skill issue zurecht",
  "digga MAX WIN IST 10000X NUR DAMIT DU WEISST WAS DU NIE SIEHST lol",
  "ok aber WAS lol",
  "wallah OMG 💀",
  "kuba erklärt uns warum das eigentlich gut war 💀",
  "alter GEHT AB das",
  "VALO AUFGEHÖRT WEIL ZU VIELE CHEATER. KLAR KUBA lmao",
  "digga shaker ist leer",
  "er traut sich nicht lmao x2",
  "JAAAA lol",
  "SELBST SCHULD",
  "alter NIEMAND ZWINGT DICH",
  "nur k und q das ganze spiel 💀",
  "chat hatte recht ez",
  "ok aber das ist zurecht so",
  "ok aber hab ich literally gesagt lmao",
  "operator gekauft, ecke geheld, nix getroffen. wie hier xd",
  "DER MANN HAT 4000 STUNDEN VALO UND TRIFFT TROTZDEM NIX 💀",
  "alter er hat den rank verloren, jetzt verliert er geld",
  "kuba war mal radiant und jetzt sitzt er hier lmao",
  "bro er atmet nicht mehr xd",
  "wallah skill issue xd",
  "ok aber er traut sich nicht lmao",
  "ok aber das board ist tot",
  "valo dienstalliert, würde nicht ändern",
  "KEIN EINZIGER MULTI ez",
  "SCATTER zurecht",
  "digga du hast es doch selber gewollt lmao",
  "alter chat hatte recht lmao",
  "digga er hat damals den crosshair code verkauft für 5 euro",
  "wallah habt ihr das gesehen !!!",
  "alter er sagt prooo, er meint premier bronze 💀",
  "whey zahlt nicht mal die miete lmao ???",
  "wallah ZURECHT BRUDER lmao",
  "ex immortal, current broke xd niemand",
  "WHEY ZAHLT NICHT MAL DIE MIETE",
  "wallah niemand zwingt dich",
  "digga peinlich aber lustig",
  "ok aber HAHA er weint gleich zurecht",
  "bro mein akkuuu ist bei 3 prozent aber ich bleib",
  "der tumble kommt nicht 💀 super",
  "board sieht krank aus ???",
  "wallah KUBA PEEKT DEN SPIN WIE NE ECKE AUF ASCENT",
  "ok aber und wieder nix ez !!!",
  "hab ich gerade nicht geblinzelt tumble",
  "DAMALS ACE, HEUTE KEINE 5 GLEICHEN ez",
  "letzter spin schwöre 💀",
  "bro kuba peekt den spin wie ne ecke auf ascent lmao",
  "bro kein einziger multi xd",
  "bro SCREENSHOT IST GEMACHT ez",
  "digga der rtp ist 96 aber nicht für dich",
  "SCREENSHOT IST GEMACHT",
  "digga ante 2 an du hast nix zu verlieren lol",
  "digga kubaaa hat seinen sheriff verkauft für den bonus buy",
  "wallah tumble tumble tumble lol",
  "bonus buy jetzt xd",
  "HAB ICHS NICHT GESAGT xd",
  "wallah noch ein scoop dann läufts",
  "alter LOS LOS LOS ich",
  "wallah atme 💀",
  "digga ich will 500x sehen",
  "kuba peekt den spin wie ne ecke auf ascent ???",
  "HAHAHA NEIN 💀",
  "kuba ist der grund warum es einen surrender button gibt lmao",
  "wallah x2 ist ne beleidigung zurecht",
  "er hat mehr zeit im slot als in der range verbracht ez",
  "sag nochmal du hast das im griff xd",
  "ich bin schon wieder timeout lol",
  "BRUDER zurecht",
  "digga kuba war der einzige der in silber geraget hat lmao",
  "wallah ich bin schon wieder timeout zurecht !!!",
  "operator gekauft, ecke geheld, nix getroffen. wie hier 💀",
  "händeee weg von der maus",
  "wallah ante 1 ist copium 💀",
  "atme lmao",
  "bro hab ich literally gesagt 💀",
  "alter kauf endlich lol",
  "er ist blass geworden ez",
  "ok aber ich hab im chat gewarnt",
  "2000 leuteee schauen ihm beim verlieren zu zurecht",
  "digga lüg dich nicht an zurecht",
  "der mann hat 4000 stunden valo und trifft trotzdem nix zurecht",
  "ICH LACH MICH WEG lmao …",
  "DAS GEHT VIRAL",
  "hahaha nein xd",
  "neuer clip zurecht",
  "HAHA er wient gleich",
  "warum bin ich noch hier lmao",
  "wallah kuba hat ein ganzes team zum aufhören gebracht lmao !!!",
  "alter board sieht ok aus",
  "ok aber kuba hat valo verlassen weil valo ihn verlassen hat",
  "wallah ER HAT DEN RANK VERLOREN, JETZT VERLIERT ER GELD",
  "digga sein team hat ihn gereportet, zurecht 💀",
  "ok aber ich hab morgen prüfung zurecht",
  "skill issue ez",
  "digga LETZTER SPIN SCHWÖRE",
  "wallah hab ich gerade nicht geblinzelt",
  "das tat weh beim zuschauen xd",
  "bro copium level 9000",
  "alter REYNA ONE TRICK ENERGIE ???",
  "alter das war absehbar",
  "alter ES GEHT LOS",
  "digga OMFG zurecht",
  "digga der letzte spin ist nie der letzte",
  "bro WHEY ZAHLT NICHT MAL DIE MIETE 💀",
  "ok aber ER IST BLASS GEWORDEN",
  "wallah multi ohne cluster ist das neue tilt zurecht",
  "UND WIEDER NIX lol",
  "ok aber zurecht lmao ???",
  "ok aber keiner atmet",
  "digga völlig zurecht xd",
  "ok aber valo deinstalliert, würde nicht ändern",
  "bro mods bannt mich 💀 tanga",
  "der hat iso gemained. zurecht xd",
  "bro warum bin ich noch hier",
  "alter er sagt pro, er meint premier bronze",
  "OPERATOR GEKAUFT, ECKE GEHELD, NIX GETROFFEN. WIE HIER ez",
  "clip it ez",
  "bro und wieder nix ez",
  "alter ich bin schon wieder timeout ez",
  "letzter spin schwöreee",
  "von valo zu slots, was für ein arc zurecht",
  "hab ichs nicht gesagt lmao",
  "valo aufgehört weil zu viele cheater. klar kuba sein",
  "bro damals ace, heute keine 5 gleichen",
  "alter der hat iso gemained. zurecht 💀",
  "alter 5 GLEICHE WÄREN MAL WAS zurecht",
  "er ist blass geworden xd",
  "er hat mehr zeit im slot als in der range verbracht lmao",
  "kuba schlaf 💀",
  "alter nicht atmen ez",
  "bro neuer clip",
  "kuba schlaf lmao",
  "ein cluster mehr und es geht ab lol",
  "digga kuba erklärt uns warum das eigentlich gut war ez",
  "wallah global multi bei 3 nach 10 spins ist crazy work",
  "ok aber ich hab morgen früh schicht 💀",
  "kubaaa erklärt uns warum das eigentlich gut war xd",
  "er traut sich nicht xd",
  "der mann hat 4000 stunden valooo und trifft trotzdem nix",
  "alter cluster wo",
  "er hat den rank verloren, jetzt verliert er geld lmao",
  "anteee 2 an du hast nix zu verlieren lmao",
  "DAS IST ZURECHT SO xd",
  "hände weg von der maus lol",
  "hab ichs nicht gesagt xd",
  "von valooo zu slots, was für ein arc lmao",
  "digga ass symbol spam lol",
  "tangaaa cluster wäre lore accurate ez",
  "bro 500x buy oder nichts ez",
  "x2 dankeee auch ez",
  "wallah kein einziger multi xd",
  "bro MODS BANNT MICH …",
  "HAHAHAHA ez",
  "ok aber kuba war der einzige der in silber geraget hat ez",
  "digga MEIN AKKU IST BEI 3 PROZENT ABER ICH BLEIB",
  "ok aber er redet sich das schön lol",
  "ICH HAB MORGEN FRÜH SCHICHT lol",
  "bro KUBA WAR DER EINZIGE DER IN SILBER GERAGET HAT",
  "bro ZWEI SCATTER REICHT NICHT 💀",
  "freispiele mit x1 global. peak 💀",
  "wallah hab ich geradeee nicht geblinzelt ez",
  "das muss auf tiktok lol",
  "DAS WAR ES",
  "first 💀",
  "digga erstmal einen shaker",
  "testo cluster wo zurecht",
  "bro peptides sind das neueee gold",
  "bro hände weg von der maus xd",
  "wallah aua",
  "bro tumble tumble tumble ez",
  "LOS LOS LOS xd",
  "digga anteee 2 an du hast nix zu verlieren lmao",
  "OPERATOR GEKAUFT, ECKE GEHELD, NIX GETROFFEN. WIE HIER xd",
  "digga SPIKE PLANTED, KONTO EXPLODED 💀",
  "wallah der spielt slots wie er valo gespielt hat. lose lose",
  "bro 5 gleiche wären mal was",
  "wallah scatter lmao",
  "digga x2 ist ne beleidigung ???",
  "bro KUBA ERKLÄRT UNS WARUM DAS EIGENTLICH GUT WAR",
  "ok aber KUBA RUHIG BLEIBEN",
  "bro ER HAT DEN RANK VERLOREN, JETZT VERLIERT ER GELD",
  "alter ich hab mich selbst enttäuscht 💀",
  "testo cluster wo lmao",
  "ok aber ich hab mich selbst enttäuscht",
  "CLUTCH OR KICK. HEUTE KICK ez",
  "warum bin ich noch hier zurecht ???",
  "schmerz 💀 ???",
  "kuba peekt den spin wie ne ecke auf ascent ez",
  "ER HAT DAMALS DEN CROSSHAIR CODE VERKAUFT FÜR 5 EURO",
  "KOSTENLOSER CONTENT lmao",
  "digga kuba war mal radiant und jetzt sitzt er hier ???",
  "ok aber völlig zurecht",
  "VALO DEINSTALLIERT, WÜRDE NICHT ÄNDERN zurecht",
  "wallah ZURECHT 💀",
  "hände weg von der maus ich",
  "das war absehbar zurecht",
  "wallah KUBA SCHLAF ez",
  "digga KUBA HAT EIN GANZES TEAM ZUM AUFHÖREN GEBRACHT 💀",
  "bro du bist nicht unlucky du bist schlecht 💀!!",
  "digga kauf den super buy du feigling zurecht",
  "ok aber kuba hat seinen sheriff verkauft für den bonus buy zurecht",
  "bro völlig zurecht",
  "bro zurecht und nicht anders lol",
  "SCATTER lol",
  "schmerz lmao …",
  "hart verdient 💀"
];
